micronaut:
  server:
    max-request-size: 104857600
    multipart:
      max-file-size: 104857600
  application:
    name: hashedpictures
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3

bin:
  token-chars: ABCDEF0123456789
  token-length: 6